before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./app/whatsthis/main.go
    goos:
    - linux
    goarch:
    - amd64
    - arm64
changelog:
  sort: desc
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
