language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt -r test-requirements.txt
script:
  - tox
  - python setup.py install
  - whatsthis version
  - whatsthis features
