name: whatsthis 
version: git
version-script: git rev-parse --short HEAD

summary: This is a Python 3 based CLI app to determine what a system is.
description: | 
  Am I in a cloud, on a container, or just plain metal? 

license: GPL-3.0

base: core18
grade: stable
confinement: strict 

apps:
  whatsthis:
    command: whatsthis
    plugs:
      - home
      - hardware-observe
      - kernel-module-observe
      - log-observe
      - mount-observe
      - network-observe
      - physical-memory-observe
      - system-observe
      - upower-observe
      #- system-files
      
parts: 
  whatsthis:
    source: https://github.com/powersj/whatsthis
    source-type: git
    plugin: python
    python-version: python3
    
    build-packages:
      - python3
      
    stage-packages:
      - python3
